iso/urls.py
from django.urls import path
from iso import views #ดึงฟังก์ชันจาก views มา
#iso

urlpatterns = [
    path('',views.HomePage,name='home-page'),
    path('news',views.NewsBlog,name='news-page'),
    path('register/',views.Register,name='register-page'),
]

isoconsult/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('iso.urls')),
    path('onsite/', include('onsite.urls')),
    path('online/', include('online.urls')),
    path('quiz/', include('app_quiz.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
]

online/urls.py
from django.urls import path
from online import views #ดึงฟังก์ชันจาก views มา
#iso

urlpatterns = [
    path('elerning',views.ElerningPage,name='elerning-page'),
    path('course/<int:code>',views.course_page,name='course-page'),
    path('addAnnouncement/<int:code>/',views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',views.updateAnnouncement, name='updateAnnouncement'),
]

online/models.py
from django.db import models
from froala_editor.fields import FroalaField

# Create your models here.
class Course(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, null=False, unique=True)
    studentKey = models.IntegerField(null=False, unique=True)
    facultyKey = models.IntegerField(null=False, unique=True)

    class Meta:
        unique_together = ('code','name')
        verbose_name_plural = "Courses"

    def __str__(self):
        return self.name


class Announcement(models.Model):
    course_code = models.ForeignKey(Course, on_delete=models.CASCADE, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    description = FroalaField(theme="dark", null=True,blank=True)

    class Meta:
        verbose_name_plural = "Announcements"
        ordering = ['-datetime']

    def __str__(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")



class Assignment(models.Model):
    course_code = models.ForeignKey(Course, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    deadline = models.DateTimeField(null=False)
    file = models.FileField(upload_to='assignments/', null=True, blank=True)
    marks = models.DecimalField(max_digits=6, decimal_places=2, null=False)

    class Meta:
        verbose_name_plural = "Assignments"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def due_date(self):
        return self.deadline.strftime("%d-%b-%y, %I:%M %p")

online/forms.py
from django import forms
from froala_editor.widgets import FroalaEditor
from .models import Announcement, Assignment


class AnnouncementForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnnouncementForm, self).__init__(*args, **kwargs)
        self.fields['description'].required = True
        self.fields['description'].label = ''

    class Meta:
        model = Announcement
        fields = ['description']
        widgets = {
            'description': FroalaEditor(),
        }


class AssignmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AssignmentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = True
            field.label = ''
        self.fields['file'].required = False

    class Meta:
        model = Assignment
        fields = ('title', 'description', 'deadline', 'marks', 'file')
        widgets = {
            'description': FroalaEditor(),
            'title': forms.TextInput(attrs={'class': 'form-control mt-1', 'id': 'title', 'name': 'title', 'placeholder': 'Title'}),
            'deadline': forms.DateTimeInput(attrs={'class': 'form-control mt-1', 'id': 'deadline', 'name': 'deadline', 'type': 'datetime-local'}),
            'marks': forms.NumberInput(attrs={'class': 'form-control mt-1', 'id': 'marks', 'name': 'marks', 'placeholder': 'Marks'}),
            'file': forms.FileInput(attrs={'class': 'form-control mt-1', 'id': 'file', 'name': 'file', 'aria-describedby': 'file', 'aria-label': 'Upload'}),
        }

online/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from online.models import Course,Announcement
from .forms import AnnouncementForm
from django.http import HttpResponse
# Create your views here.

def ElerningPage(request):
    courses = Course.objects.all()
    return render(request,"elerning.html",{"courses":courses})

def course_page(request,code):
    #try:
        course = Course.objects.get(code = code)
        announcements = Announcement.objects.filter(course_code=course)

        context = {
            'course':course,
            'announcements': announcements,
            }
        return render(request,"course.html",context)
    
    #except:
        return HttpResponse("<h1><center>Error</h1>")


def addAnnouncement(request, code):
    if request.method == 'POST':
            form = AnnouncementForm(request.POST)
            form.instance.course_code = Course.objects.get(code=code)
            if form.is_valid():
                form.save()
                return redirect('course-page', code=code)
                
    else:
        form = AnnouncementForm()
    return render(request, 'announcement.html', {'course': Course.objects.get(code=code), 'form': form})


def deleteAnnouncement(request, code, id):
        try:
            announcement = Announcement.objects.get(course_code=code, id=id)
            announcement.delete()
            messages.warning(request, 'Announcement deleted successfully.')
            return redirect('course-page', code=code)
        except:
            return redirect('course-page', code=code)


def editAnnouncement(request, code, id):
        announcement = Announcement.objects.get(course_code_id=code, id=id)
        form = AnnouncementForm(instance=announcement)
        context = {
            'announcement': announcement,
            'course': Course.objects.get(code=code),
            'form': form
        }
        return render(request, 'update-announcement.html', context)


def updateAnnouncement(request, code, id):
        try:
            announcement = Announcement.objects.get(course_code_id=code, id=id)
            form = AnnouncementForm(request.POST, instance=announcement)
            if form.is_valid():
                form.save()
                messages.info(request, 'Announcement updated successfully.')
                return redirect('course-page', code=code)
        except:
            return redirect('course-page', code=code)

online/templates/announcement.html
{% extends 'iso/components/base.html' %}
{% load static %}
{% block title %} <title>addAnnouncement</title> {% endblock %}

{% block content %}
<div class="container mt-4 mb-5">
   <div class="container mt shadow-sm">
      <nav
         style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"
         aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)" href="{% url 'elerning-page' %}">My courses</a>
            </li>
            <li class="breadcrumb-item fw-bold">
               <a style="color: rgb(10, 10, 48)" href="{% url 'course-page' course.code%}">{{ course.name }}</a>
            </li>
            <li class="breadcrumb-item active animate__animated animate__backInRight" aria-current="page">Announcement</li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container">
      <div class="row justify-content-center">
         <div class="col-md-8 shadow-lg p-3 rounded">
            <div class="text-center">
               <div class="fw-bold mb-3 text-start">Post Announcement</div>
               <div class="from-group">
                  <form method="post" enctype="multipart/form-data">
                     {% csrf_token %}
                     {{ form.as_p }}
                     <!-- submit button -->
                     <div class="d-flex justify-content-end bg-light border p-2 rounded">
                        <a class="btn btn-sm btn-outline-danger mx-2" href="{% url 'course-page' course.code%}">Cancel</a>
                        <button class="btn btn-sm btn-primary" type="submit" id="submit"> <span class="mx-2">Post</span></button>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

online/templates/course.html
{% extends 'iso/components/base.html' %}
{% block title %} <title>Course</title> {% endblock %}
{% block content %}
{% load static %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
   <span> {{ message }}</span>
   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% comment %} alert ends {% endcomment %}
<div class="container mt-4 mb-5">
   <div class="container shadow-sm">
      <nav
         style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"
         aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)" href="{% url 'elerning-page' %}">My
                  Courses</a>
            </li>
            <li class="breadcrumb-item fw-bold animate__animated animate__backInRight"><a class="breadcrumb-item active"
                  aria-current="page">{{ course.name }}</a></li>
         </ol>
      </nav>
   </div>
   <div class="container d-flex flex-wrap flex-column">
      <!-- course name starts -->
      <div class="rounded p-3 m-3 shadow d-flex justify-content-between">
         <span></span>
         <h5 class="mt-2 fw-bold">Course : {{course.name}}</h5>
         <div class="dropdown">
            <img class="dropdown-toggle" id="drop" data-bs-toggle="dropdown" aria-expanded="false"
               src="{% static '/images/icon/dropDown.png' %}" alt="Options" height="32">
            <ul class="dropdown-menu">
               <li class="border-bottom">
                  <a class="dropdown-item" href="#discus">
                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-chat-right-dots mx-2" viewBox="0 0 16 16">
                        <path
                           d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z" />
                        <path
                           d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                     </svg>
                     Discussion
                  </a>
               </li>
               {% if user.is_staff %}
               <li class="border-bottom">
                  <a class="dropdown-item" href="{% url 'allQuizzes' course.code %}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-person-check mx-2" viewBox="0 0 16 16">
                        <path
                           d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                        <path fill-rule="evenodd"
                           d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
                     </svg>
                     Add Quiz
                  </a>
               </li>
               {% endif %}
               <li>
                  <a class="dropdown-item" href="{% url 'myQuizzes' course.code %}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-card-text mx-2" viewBox="0 0 16 16">
                        <path
                           d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                        <path
                           d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                     </svg>
                     Quiz
                  </a>
               </li>
            </ul>
         </div>
      </div>
      <!-- course name ends -->
      <!-- announcement section starts -->
      <div class="rounded p-3 m-3 shadow border border-top-0 border-end-0 border-bottom-0 border-primary border-5">
         <div class="animate__animated animate__zoomInDown d-flex justify-content-between border-bottom border-1 mb-2">
            <img src="{% static 'images/icon/megaphone.png' %}" style="height:1.5rem; vertical-align: text-bottom;">
            <div>
               <h5 class="fw-bold" style="color: rgb(10, 10, 48);">Announcement</h5>
            </div>
            {% if user.is_staff %}
            <a href="{% url 'addAnnouncement' course.code  %}"><img src="{% static 'images/icon/iconBlack.png' %}"
                  alt="" height="32"></a>
            {% else %}
            <img src="{% static 'images/icon/megaphone.png' %}" style="height:1.5rem; vertical-align: text-bottom;">
            {% endif %}
         </div>
         <div>
            {% for announcement in announcements %}
            <!-- individual announcement starts -->
            <div class="fs-6 text-wrap text-break" id="annDescription{{announcement.id}}">{% autoescape off %}{{announcement.description}}{% endautoescape %}</div>
            <div class="d-flex justify-content-between">
               {% if user.is_staff %}
               <div>
                  <button type="button" class="btn btn-sm btn-outline-danger" style="border:none" data-bs-toggle="modal"
                     data-bs-target="#announcement{{announcement.id}}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor"
                        class="bi bi-trash" viewBox="0 0 16 16">
                        <path
                           d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                        <path fill-rule="evenodd"
                           d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                     </svg>
                     <span style="vertical-align:middle">Delete</span>
                  </button>
                  <!-- Popup -->
                  <div class="modal fade" id="announcement{{announcement.id}}" data-bs-backdrop="static"
                     data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                     <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                           <div class="modal-header" style="border:none">
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                              </button>
                           </div>
                           <div class="modal-body fs-6">
                              Are you sure you want to delete this announcement?
                           </div>
                           <div class="modal-footer" style="border:none">
                              <button type="button" data-bs-dismiss="modal" class="btn btn-sm ">Cancel</button>
                              <a class="btn btn-sm btn-primary" href="{% url 'deleteAnnouncement' course.code announcement.id %}">Confirm</a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <a class="btn btn-sm btn-outline-success" style="border:none"
                     href="{% url 'editAnnouncement' course.code announcement.id %}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor"
                        class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path
                           d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                        <path fill-rule="evenodd"
                           d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                     </svg>
                     <span style="vertical-align:middle">Edit</span>
                  </a>
               </div>
               {% endif %}
               <div class="add-announcement" style="color:grey;">
                  {{announcement.post_date}}
               </div>
            </div>
            <hr>
            <!-- individual announcement ends-->
            {% empty %}
            <p class="fs-6 text-center text-muted">No announcement has been posted</p>
            {% endfor %}
         </div>
      </div>
      <!-- announcement section ends -->
      <!-- assignment section starts -->
      <div class="rounded p-3 m-3 shadow border border-top-0 border-bottom-0 border-end-0 border-danger border-5 mb-2">
         <div class="fw-bold fs-5 text-center animate__animated animate__zoomInDown border-bottom border-1 mb-2 py-2"
            style="color: rgb(10, 10, 48);"><img src="" alt="" style="height:1.5rem; vertical-align: text-top"><span
               style="margin-right: 0.6rem;"></span>Assignment</div>
         <div>
            {% for assignment in assignments %}
            <!-- individual assignment starts -->
            <a class="fw-bold" href="{% url 'assignmentPage' course.code assignment.id %}">{{assignment.title}}</a>
            <div class="d-flex justify-content-between">
               <p style="font-size:15px"> Due Date : {{ assignment.due_date}} </p>
               <div style="color:grey;">
                  {{assignment.post_date}}
               </div>
            </div>
            <!-- individual assignment ends -->
            {% empty %}
            <p class="text-center text-muted fs-6">No assignments given yet</p>
            {% endfor %}
         </div>
         {% if assignments %}
         <div class="text-center fs-6 text-muted d-flex flex-column border-top border-1">
            <span class="mt-2">Showing {{ assignments.count}} of {{course.assignment_set.count}}
               {% if assignments.count == 1 %}assignment {% else %}assignments{% endif %}
            </span>
            <a class="fs-6" href=" {% url 'student-assignments' course.code %} ">Show all</a>
         </div>
         {% endif %}
      </div>
      <!-- assignment section ends -->
      <!-- course material section starts -->
      <div class="rounded p-3 m-3 shadow border border-top-0 border-bottom-0 border-warning border-end-0 border-5"
         id="material">
         <!-- section title -->
         <div class="fw-bold animate__animated animate__zoomInDown fs-5 text-center border-bottom border-1 mb-2 py-2"
            style="color: rgb(10, 10, 48);"><img src="" alt="" style="height:1.5rem;vertical-align: text-top"><span
               style="margin-right: 0.6rem;"></span>Course Material</div>
         <!-- section title ends -->
         <div>
            {% for material in materials %}
            <!-- individual material starts -->
            <p>{% autoescape off %}{{ material.description }}{% endautoescape %}</p>
            <div class="d-flex justify-content-between text-break">
               {% if material.file %}
               <a class="fw-bold" href="{{ material.file.url }}"><span style="color:#9400d3" id="materialName">File :
                     {{material.file.name}}</span></a><br>
               {% endif %}
               <div class="text-muted">
                  {{material.post_date}}
               </div>
            </div>
            {% empty %}
            <p class="text-center text-muted fs-6">Course materials not available</p>
            {% endfor %}
            <!-- individual material ends -->
         </div>
      </div>
      <!-- course material section ends -->
   </div>

</div>

{% endblock %}

online/templates/elerning.html
{% extends 'iso/components/base.html' %}
{% block title %} <title>Elerning</title> {% endblock %}

{% block content %}

<div class="container mt-4 mb-5">
   <div class="container shadow-sm">
      <nav
         style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"
         aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item active animate__animated animate__backInRight" aria-current="page">All courses
            </li>
         </ol>
      </nav>
   </div>

   <h2 class="text-center">Elerning</h2>
   <div class="row gy-5 mt-1">
      {% for course in courses %}
      <div class="col-sm-6 d-flex align-items-stretch justify-content-center animate__animated animate__zoomIn">
         <div class="card shadow" style="width: 30rem !important;">
            <div class="class-header text-center text-light border-bottom bg-dark rounded">
               <h6 class="my-2"> Dept. of </h6>
            </div>
            <div class="card-body d-flex flex-column align-items-center">
               <h5 class="card-title fw-bold">{{course.name}}</h5>

               <p class="card-text fw-bold">Course Teacher : อาจารย์</p>

               <p> Teacher not assigned</p>
               <a href="{% url 'course-page' course.code %}" class="btn btn-outline-dark"><span
                     class="px-3">Enter</span></a>

            </div>
         </div>
      </div>
      {% endfor %}
   </div>
</div>

{% endblock %}

online/templates/update-announcement.html
{% extends 'iso/components/base.html' %}
{% load static %}
{% block title %} <title>addAnnouncement</title> {% endblock %}

{% block content %}
<div class="container mt-4 mb-5">

   <div class="container mt shadow-sm">
      <nav
         style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"
         aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)" href="{% url 'elerning-page' %}">My
                  courses</a>
            </li>
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
                  href="{% url 'course-page' course.code%}">{{ course.name }}</a></li>
            <li class="breadcrumb-item active animate__animated animate__backInRight" aria-current="page">Announcement</li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container">
      <div class="row justify-content-center">
         <div class="col-md-8 shadow-lg p-3 rounded">
            <div class="text-center">
               <div class="fw-bold mb-3 text-start">Edit Announcement</div>
               <div class="from-group">
                <form action="{% url 'updateAnnouncement' course.code announcement.id %}" method="post" enctype="multipart/form-data">
                     {% csrf_token %}
                     {{ form.as_p }}
                     <!-- submit button -->
                     <div class="d-flex justify-content-end bg-light border p-2 rounded">
                        <a class="btn btn-sm btn-outline-danger mx-2" href="{% url 'course-page' course.code%}">Cancel</a>
                        <button class="btn btn-sm btn-primary" type="submit" id="submit"> <span class="mx-2">Post</span></button>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>

</div>
{% endblock %}